platformName: Android

appPackage: com.intsig.BizCardReader
appActivity: com.intsig.camcard.BcrFirstLaunchGuide

noReset: True
unicodeKyeboard: True
resetKeyboard: True
automationName: Uiautomator2

ip: 127.0.0.1
